name: Create Archive
on: 
  push:
        branches:
            - main
jobs:
  build:
    runs-on: ubuntu-latest

    permissions: write-all
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Generate release tag
      id: release_tag
      uses: amitsingh-007/next-release-tag@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'v'
        tag_template: 'yy.mm.dd.i'
    - name: Archive
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: '${{ github.event.repository.name }}-${{ steps.release_tag.outputs.next_release_tag }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig /*Assets/* LICENSE README.md'
    - name: Release
      uses: softprops/action-gh-release@master  
      with:
        name: ${{ steps.release_tag.outputs.next_release_tag }}
        tag_name: ${{ steps.release_tag.outputs.next_release_tag }}
        generate_release_notes: true
        files: ${{ github.event.repository.name }}-${{ steps.release_tag.outputs.next_release_tag }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
